### ISSUE TITLE
Implement Build Automation (Cake)

### ISSUE THREAD

**Issue by scottoffen** [sukona/Grapevine#125]
Needs to be able to:
- Build for multiple target platforms
- Execute unit tests on each target platform
- Push unit test results and code coverage to SonarQube
- Build and publish NuGet under specific conditions
  - It should not build and publish the NuGet every time
  - Only if specified test suites pass
  - Only on the `master` branch
  - Only when tagged as a release

**Comment by emanuelmd** [comment]
Hello, I've been trying for the past few hours to implement a build system with Cake, but I'm stuck the compiler error CS0426 "The nested type `ExtendedProtectionSelector` does not exist on type `System.Net.HttpListener` " in files RestServer.cs and IHttpListener.cs

I'm trying to make this work on Arch Linux using mono version 4.4.1

**Comment by scottoffen** [comment]
Currently, Grapevine only targets the .NET 4.0 platform. There are open tickets to target the newer platforms, but they are a few weeks out from being implemented.

**Comment by emanuelmd** [comment]
The ExtendedProtectionSelector exists in the Mono implementation. I'd gladly test and run the project on linux when you guys are ready with that. Meanwhile I'll dig around, and see if I can do that Cake build system.

**Comment by scottoffen** [comment]
@emanuelmd Shoot me an email if you'd like to get a hold of you when we are ready for that.
